SNAPSHOT deploy to GitHub Packages returns 401 .. Trying some debug ..

diff --git a/.github/workflows/3.x.maven.yml b/.github/workflows/3.x.maven.yml
--- a/.github/workflows/3.x.maven.yml
+++ b/.github/workflows/3.x.maven.yml
@@ -59,11 +59,15 @@ jobs:
         server-id: github
         server-username: ${{github.actor}}
         server-password: ${{secrets.GITHUB_TOKEN}}
+    - name: Debug settings.xml
+      run: |
+        echo "Contents of ~/.m2/settings.xml:"
+        cat ~/.m2/settings.xml || echo "settings.xml not found"
     - name: Extract project version
       id: project
       run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
     - name: Deploy with Maven
       if: ${{endsWith(steps.project.outputs.version, '-SNAPSHOT')}}
-      run: mvn -B deploy -Dmaven.test.skip=true
+      run: mvn -B deploy -Dmaven.test.skip=true -X
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
